'use client';
import { useEffect, useMemo, useState } from 'react';
type Product = { _id: string; name: string; description?: string; imageUrl?: string; price: number; promotionalPrice?: number; categoryId: string };
type Restaurant = { _id: string; name: string; description?: string; bannerUrl?: string; logoUrl?: string; open: boolean; settings?: { deliveryFee?: number } };
const money = (value: number) => value.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });
export function Menu({ slug }: { slug: string }) { const [restaurant, setRestaurant] = useState<Restaurant>(); const [products, setProducts] = useState<Product[]>([]); const [cart, setCart] = useState<Product[]>([]); const api = process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:3001';
 useEffect(() => { void (async () => { const r = await fetch(`${api}/restaurants/${slug}`); if (!r.ok) return; const restaurantData = await r.json() as Restaurant; setRestaurant(restaurantData); const p = await fetch(`${api}/restaurants/${restaurantData._id}/products`); if (p.ok) setProducts(await p.json() as Product[]); })(); }, [api, slug]);
 const subtotal = useMemo(() => cart.reduce((sum, product) => sum + (product.promotionalPrice ?? product.price), 0), [cart]);
 if (!restaurant) return <main className="mx-auto max-w-lg p-6"><div className="h-52 animate-pulse rounded-3xl bg-stone-200" /><p className="mt-5 text-stone-500">Carregando cardápio…</p></main>;
 return <main className="mx-auto min-h-screen max-w-lg pb-32"><header className="relative h-56 bg-ink" style={restaurant.bannerUrl ? { backgroundImage: `linear-gradient(#17201b88,#17201baa),url(${restaurant.bannerUrl})`, backgroundSize: 'cover' } : undefined}><div className="absolute inset-x-5 bottom-5 text-white"><span className={`inline-block rounded-full px-3 py-1 text-xs font-bold ${restaurant.open ? 'bg-lime text-ink' : 'bg-red-500'}`}>{restaurant.open ? 'ABERTO AGORA' : 'FECHADO'}</span><h1 className="mt-3 text-3xl font-black">{restaurant.name}</h1><p className="mt-1 text-sm text-stone-200">{restaurant.description ?? 'Entrega • Retirada no estabelecimento'}</p></div></header><section className="px-4 pt-6"><h2 className="text-xl font-black">Peça o que quiser</h2><p className="mt-1 text-sm text-stone-500">Produtos preparados com carinho para você.</p><div className="mt-5 grid gap-3">{products.length === 0 ? <div className="rounded-2xl bg-white p-6 text-center text-stone-500 shadow-soft">Nenhum produto disponível no momento.</div> : products.map(product => <article key={product._id} className="flex gap-4 rounded-2xl bg-white p-3 shadow-soft"><div className="h-24 w-24 shrink-0 rounded-xl bg-stone-100" style={product.imageUrl ? { backgroundImage: `url(${product.imageUrl})`, backgroundSize: 'cover', backgroundPosition: 'center' } : undefined} /><div className="min-w-0 flex-1"><h3 className="font-bold">{product.name}</h3><p className="mt-1 line-clamp-2 text-sm text-stone-500">{product.description}</p><div className="mt-3 flex items-center justify-between"><b>{money(product.promotionalPrice ?? product.price)}</b><button disabled={!restaurant.open} onClick={() => setCart([...cart, product])} className="rounded-xl bg-ink px-4 py-2 text-sm font-bold text-white disabled:opacity-40">Adicionar</button></div></div></article>)}</div></section>{cart.length > 0 && <aside className="fixed inset-x-0 bottom-0 z-10 mx-auto max-w-lg border-t bg-white p-4 shadow-2xl"><div className="mb-3 flex justify-between text-sm"><span>{cart.length} item(ns) no pedido</span><b>{money(subtotal)}</b></div><button className="w-full rounded-xl bg-lime py-4 font-black text-ink">VER SACOLA</button></aside>}</main>; }
